version: '3.3' 

services:
  my-frontend:
    build:
      context: ./frontend
    container_name: vite
    depends_on:
      - my-java
    ports:
      - "3456:80"
    command: [nginx-debug, '-g', 'daemon off;']

  my-java:
    build: 
      context: ./backend
    container_name: my-java
    depends_on:
      - postgres  
    environment:
      - SQL_SERVER=postgres
      - DATABASE=${DATABASE}
      - LOG_FOLDER=${LOG_FOLDER}
      - PASSWORD=${PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - USERNAME=${USERNAME}
      - SQL_PORT=${SQL_PORT}
  
  postgres:
    build:
      context: ./db
    container_name: postgres
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
        #  volumes:
        # - db_script:/docker-entrypoint-initdb.d/init-db.sh
        # - db_file:/docker-entrypoint-initdb.d
        # command: ["bash", "/docker-entrypoint-initdb.d/init-db.sh"]
  
