POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Other idi1t",
  "password": "dfs",
  "email": "dsfds",
  "reviews": []
}

###
POST http://localhost:8080/api/publishers
Content-Type: application/json

{
  "publisherName": "IOfd",
  "boardGames": []
}

###

DELETE http://localhost:8080/api/categories/84caafb5-7b38-4914-af88-6b8cd094e3cb


###

POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "name": "Super",
  "description": "Super",
  "boardGames": []
}
###


POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "test_name",
  "password": "password",
  "email": "email",
  "reviews": []
}


###

POST http://localhost:8080/api/reviews
Content-Type: application/json

{
  "description": "Amazddddding",
  "boardGamePublicID": "89925c17-cf11-448c-af83-7a94d67ccc49",
  "appUserPublicID": "0de68408-c461-43d4-902a-f2abe560a6a3"
}

###

POST http://localhost:8080/api/reviews
Content-Type: application/json

{
"description": "test_vol",
"boardGamePublicID": "e5141cf6-7a46-41e8-b877-3eb64fc86958",
"appUserPublicID": "780973ac-715e-415c-abd1-b74f11e81bd6"
}

###
POST http://localhost:8080/api/appusers
Content-Type: application/json

{
}

###

###
POST http://localhost:8080/api/games
Content-Type: application/json

{
  "gameName": "Splendor",
  "minPlayer": 3,
  "maxPlayer": 7,
  "playTimeInMinutes": 20,
  "recommendedAge": 20,
  "description": "dfdsfds",
  "rating": 1.2,
  "reviews": [],
  "categories": [],
  "publisherPublicID": "63547281-48b6-489a-bab2-dc82f265a38d"
}


###
